apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson:  ewoJImF1dGhzIjogewoJCSJ2YWxheHk0MjAxLmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJhR0Z5YVdoaGNtRndjbUZ6WVdRME1qWTVPa2hoY21rME1qQXgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson